# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseChatting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseChatting
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseUI'
end
